// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkCNN0f5XwNMJBUuHnCvThIy9Es2Sk8UQ',
    appId: '1:35928314843:web:32eed544a6348fdc24cdfe',
    messagingSenderId: '35928314843',
    projectId: 'whatsup-79e33',
    authDomain: 'whatsup-79e33.firebaseapp.com',
    storageBucket: 'whatsup-79e33.appspot.com',
    measurementId: 'G-C042F2XZJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp9eJIWOq7VRZZlfV9_OoFfs8cd4enttM',
    appId: '1:35928314843:android:e89e5550561a6c0a24cdfe',
    messagingSenderId: '35928314843',
    projectId: 'whatsup-79e33',
    storageBucket: 'whatsup-79e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBILi-H1sgH4e25CqJuukZyHvtpcx5dixA',
    appId: '1:35928314843:ios:12958327ef1145e024cdfe',
    messagingSenderId: '35928314843',
    projectId: 'whatsup-79e33',
    storageBucket: 'whatsup-79e33.appspot.com',
    androidClientId: '35928314843-dsu1gb2s33cv7kkjdoa4dpqdr26q2ajp.apps.googleusercontent.com',
    iosClientId: '35928314843-n8gktmhfk6m1v4j30bullg94lmjmol7a.apps.googleusercontent.com',
    iosBundleId: 'studio.giangbb.whatsup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBILi-H1sgH4e25CqJuukZyHvtpcx5dixA',
    appId: '1:35928314843:ios:12958327ef1145e024cdfe',
    messagingSenderId: '35928314843',
    projectId: 'whatsup-79e33',
    storageBucket: 'whatsup-79e33.appspot.com',
    androidClientId: '35928314843-dsu1gb2s33cv7kkjdoa4dpqdr26q2ajp.apps.googleusercontent.com',
    iosClientId: '35928314843-n8gktmhfk6m1v4j30bullg94lmjmol7a.apps.googleusercontent.com',
    iosBundleId: 'studio.giangbb.whatsup',
  );
}
